# Generated by Django 4.0.3 on 2023-04-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_mng', '0002_alter_attendance_check_in_alter_attendance_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
