# Generated by Django 4.0.3 on 2023-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_mng', '0003_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
